### PR TITLE
Fix: replace createClass to be compatible with React 16

### PR DESCRIPTION
**Pull request by philquinn**
## Description
createClass has been deprecated and no longer exists in React 16. We want to upgrade to 16 but are blocked by this. I ran the codemod to replace createClass. Some had to be manually done. 

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features) - N/A
- [x] Docs have been added / updated (for bug fixes / features) -N/A

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

Uses deprecated createClass

**What is the new behavior?**

No longer uses createClass. Same behavior.

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by philquinn** [comment]
@malonecj can you give this a look please?

**Comment by philquinn** [comment]
@malonecj No problem. Thanks for merging

**Comment by PaulInglis** [comment]
Do we have any time frame for when this will make it into a release?

**Comment by wKovacs64** [comment]
@PaulInglis It's been live since 2.0.61.

**Pull request merged**
