### PR TITLE
get React 15 off the ground

### PR DESCRIPTION
**Pull request by jpdriver**
## Description

this PR is a jumping-off point for updating RDG to React 15. so far all the tests are passing, after a couple of minor changes..

we were still using `setProps` in some of the specs so I've switched us over to use enzyme `mount()`.

enzyme was already a dependency, and enzyme wrappers have a `setProps` utility method for testing the way we are doing it..

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Other... Please describe: changing React version
```

**What is the current behavior?** (You can also link to an open issue here)
We use React 14.

**What is the new behavior?**
We use React 15.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
- for now, uses a separately upgraded fork of `ron-react-autocomplete`
- Examples working locally; can use All Features Immutable as expected

There's more to do with this, and I have no idea about IE 8 support (good luck gents!) but this is a start and seems ok so far.. 🙂
## Screenshots

**React 14**
react 14

**React 15**
screen shot 2016-08-13 at 3 55 22 pm
screen shot 2016-08-13 at 4 14 57 pm

### CODE REVIEW

**Comment by jpdriver** [comment]
@malonecj any idea why when i run `gulp test` (or test debug) Karma only shows 283 tests but when we run on AV we get 310? had a quick scan of the build log -- they are genuine failures..

E.g. one thing I've noticed in my (RCT 15) app is the header cells no longer stay in line with the columns when your scroll horizontally -- which wasn't flagged locally but luckily *was* flagged by AV..

**Comment by malonecj** [comment]
@jpdriver you need to run the tests in release mode to pick up all the tests (unit + integration) ```gulp test --release```

**Comment by rudin** [comment]
Great to see react-data-grid updated to React 15! I have one issue with this fork though. Running 'npm run prepublish' gives an error:

`/Users/rudin/Projects/App/node_modules/react-data-grid/gulp/tasks/bundle.js:5
  throw new gutil.PluginError(ctx, err);
  ^
Error: ./src/ReactDataGrid.js
Module parse failed: /Users/rudin/Projects/App/node_modules/react-data-grid/src/ReactDataGrid.js Unexpected token (19:5)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (19:5)
    at Parser.pp$4.raise (/Users/rudin/Projects/App/node_modules/react-data-grid/node_modules/webpack/node_modules/acorn/dist/acorn.js:2221:15)`

Any idea? Anybody having thesame issue?
...or is there a 'dist' version for download someplace?

**Comment by jpdriver** [comment]
hey @rudin -- please be aware that this fork / PR is *super* super alpha stage. It can and will change over time, and definitely *is not production ready*.

I haven't seen your issue before -- can you try `npm gulp` rather than prepublish to get the usual examples up? That works for me, and tbh right now I'm doing that then copying the generated `dist` folder out to my RCT 15 project and committing it into source control..

There are still lots of bugs and things that just plain don't work with this version though. Seriously, unless you absolutely absolutely absolutely *have* to use this -- don't.

Stick to React 14, and what Adazzle actually supports.

**Comment by jpdriver** [comment]
hey @malonecj -- i've updated this PR with a slightly revised change set. it's now back up to date with the latest RDG master and is using 15.4.1..

all tests passing (even in release mode) and **none** are commented out this time 😊

**Comment by UnbrandedTech** [comment]
+1 Would LOVE to use this in my project, but we have a hard dependency on React 15.

**Comment by erikschlegel** [comment]
Same here. We have the React 15 dependency and would LOVE to use this component. Can the library  please opine to this PR.

**Comment by frankbolviken** [comment]
I really don't see the point in not merging this. Can't people who are dependent on another version of react just install a specific version of this component? I would think it's quite dangerous to start lagging behind this early.

**Comment by jpdriver** [comment]
hey @frankbolviken -- this hasn't been merged (and likely won't be for a while) for some internal business reasons; namely the need to keep IE 8 support in the base grid. hopefully either this PR or something based on it will eventually get merged in, but there's no timeline for that just at the moment.

**Comment by batjko** [comment]
Sounds like a fork could be created, at least temporarily, to get the v15 support out there, and whenever those "internal business reasons" have moved on, both repos could be merged back together.

**Comment by jpdriver** [comment]
yep that's exactly what this is PR is. it's from a React 15 fork that I maintain, going back into the original master.

but it's more for reference than a "this is going to be merged in the next few days".

**Comment by emorling** [comment]
How do I install this? is this the cm-react-15 branch?

**Comment by emorling** [comment]
I was able to try this and still get many unmet dependencies on install. Is this to be expected?

**Comment by diogofcunha** [comment]
React 15 is out now, will close

**Pull request closed without merging**
