### PR TITLE
Fix false positive getDefaultProps warnings 

### LINKED ISSUE #978: Getting getDefaultProps warnings with react 15.6+
### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [x] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details
current behavior:
```
Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.
```
image

desired behavior: no warnings

motivation: less noise in console warnings and compatibility to upgrade React

### PR DESCRIPTION
**Pull request by amanmahajan7**
## Description
Fix false positive getDefaultProps warnings. Fixes #978

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
`React 15.5` deprecated `React.createClass` and added a warning when `getDefaultProps()` method is used with class components (`React.component`). These deprecation warnings are only shown in development mode. Components created using `React.createClass` or `createReactClass` still use `getDefaultProps()` method to define `defaultProps`. In development mode, `React` [sets a flag](https://github.com/facebook/react/blob/v15.5.4/addons/create-react-class/create-react-class.js#L718) `isReactClassApproved` to suppress these warnings for components created using `React.createClass` or `createReactClass`.
`react-data-grid.js` bundles the `min` version of `create-react-class` (created using webpack) and because of this `isReactClassApproved` flag is not set anymore on the components created using `React.createClass` or `createReactClass`.

**What is the new behavior?**
`create-react-class` is now specified as a peer dependency so it becomes the responsibility of individual project to include it. This would also require a major version bump as this is a breaking change

**Does this PR introduce a breaking change?** (check one with "x")
```
[x] Yes
[ ] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...
React data grid now has a dependency on `create-react-class` package and after upgrading to the new version (v3) one must install `create-react-class` package

**Other information**:

### CODE REVIEW

**Comment by amanmahajan7** [comment]
I am debating whether to include `prop-types` in the bundle or not. The following libraries bundle `prop-types`
`react-bootstrap`
`react-redux`

Here is an explanation from Dan Abramov : https://github.com/cssinjs/react-jss/issues/164#issuecomment-337283165

However Facebook recommends excluding `prop-types`
https://github.com/facebook/prop-types#how-to-depend-on-this-package

> For UMD bundles of your components, make sure you don’t include PropTypes in the build. Usually this is done by marking it as an external (the specifics depend on your bundler), just like you do with React.

@malonecj @diogofcunha  Thoughts?

**Comment by malonecj** [comment]
@amanmahajan7 I'm just checking the readme of prop-types

```
How to Depend on This Package?
For apps, we recommend putting it in dependencies with a caret range. For example:

  "dependencies": {
    "prop-types": "^15.5.7" 
  }
For libraries, we also recommend leaving it in dependencies:
```

I think its safest to put this in the dependencies. I see they also do that in react-router.

**Comment by diogofcunha** [comment]
Hey @amanmahajan7.

I think this is correct, we don't really want to force people using static typing having to specify prop-types dependecy, it's also important to mention that prop-types package is tiny ([see here](https://unpkg.com/prop-types@15.6.0/))

**Comment by tazabreu** [comment]
Any plans on merging and releasing this soon? This would mean a go on the usage of react-data-grid on the project that I am currently working on

**Pull request merged**
