### PR TITLE
Remove support for getRowMetaData, dependentValues, rowMetaData

### PR DESCRIPTION
**Pull request by MayhemYDG**
To be merged into `canary` once `canary` stabilizes and we merge it onto `next`.

### CODE REVIEW

**Comment by MayhemYDG** [comment]
@amanmahajan7 IMO, seeing the glacial pace at which we can adopt the ongoing rdg work, we may as well merge this now, or we'll have to wait for another 6-12 months.

**Comment by amanmahajan7** [comment]
@qili26  are you okay with merging this PR?

**Comment by qili26** [comment]
Yes, I think we could merge this. However, I think we should add something to the migration plan later, like for a shot time, you can customize like 
```
const cellRenderer = () => {
  // not from column anymore, if the dev prefer, they can accommodate the logic here.
  const metaData = getRowMetaData(); 
  return <CellContent value={metaData.value} />;
}
```

**Comment by MayhemYDG** [comment]
Yes devs can either wrap their formatters on a per-column basis, if they're using the legacy cell content renderer, or edit their custom cell content renderers, shouldn't be too much of an issue I think.

**Pull request merged**
