### PR TITLE
Allow developer to configure auto focus on the grid (addresses #813)

### PR DESCRIPTION
**Pull request by supamanda**
## Description
A PR to allow developer to configure whether the grid should steal focus when the browser is focused on the body.  Addresses #813 

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[x ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
The grid steals focus when the browser is focused on the body, see #813 

**What is the new behavior?**
Allow developer to configure whether grid should autofocus when browser is focused on the body

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x ] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by theunixbeard** [comment]
:+1: This PR looks great, Amanda, and would really help w/ my app as well.

It seems like any app w/ a complex enough UI to require scrolling would run into this issue, so it's definitely important.

Though referencing the solution in my older PR from a few months back (https://github.com/adazzle/react-data-grid/pull/704), this video demonstrates the problem in any easy to understand manner: https://www.youtube.com/watch?v=xejQdVGJX6w

With the configuration flag in Amanda's solution, app's like mine and Mike's (https://github.com/adazzle/react-data-grid/issues/813) could simply set the flag to false and get the behavior we want while leaving everyone else unaffected.

@malonecj any thoughts on this? Seems like there are no conflicts to a merge.

**Comment by thom801** [comment]
@supamanda I am also needing this feature. Can this be merged? Any way I can help?

**Comment by supamanda** [comment]
hi @thom801  , I just fixed the merge conflicts, so it's good to go again. In the meantime, I've come up with a workaround I'd be happy to share with you if you need it

**Comment by scrambled2k3** [comment]
Any time frame on when this can get merged in?  I too am experiencing this and would love to disable it.

**Comment by cohuttaboy79** [comment]
I am also having this issue and having the ability to disable the functionality would be much appreciated.

**Comment by scrambled2k3** [comment]
@supamanda would you mind sharing with me your workaround?

**Comment by supamanda** [comment]
hi @scrambled2k3 
My work around is to define my own row renderer, and override the checkFocus function; and then define my own Grid which uses the my row renderer. Code attached :)

[noautofocus.zip](https://github.com/adazzle/react-data-grid/files/1444543/noautofocus.zip)

**Pull request merged**
