### PR TITLE
Date/date-time filters

### PR DESCRIPTION
**Pull request by ben-freenome**
## Description
A few sentences describing the overall goals of the pull request's commits.

**Please check if the PR fulfills these requirements**
- [X] The commit message follows our guidelines: https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
Cannot filter on date/date-time

**What is the new behavior?**
can filter on date/date-time (assuming all dates are input as UTC and user wants to search in local time)

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[X] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by FreekKalter** [comment]
Nice, was going to write something like this myself. thnx

**Comment by malonecj** [comment]
Could you add this to the custom filters example please, and we will merge in

**Comment by ben-freenome** [comment]
I've added DateFilter to the Custom Filters example, as asked. I'd be interested in getting some styling feedback, especially for the 'including' element, as it's rather cluttered.

**Comment by ben-freenome** [comment]
This is ready to go, if anyone wants to take a look.

**Comment by madhan-dhamodaran** [comment]
Hi All,
@malonecj 
Is there any timeframe when this can go live? I am waiting for the datetime-filter. 

Kindly advise.

Thanks,
Madhan

**Pull request closed without merging**
