### PR TITLE
Support for Server Side Rendering

### PR DESCRIPTION
**Pull request by rconard**
## Description

I am a huge fan of ReactDataGrid, and I have used it extensively across projects for years. No other libraries come close to the breadth and depth of features and customization, and I am very grateful to all the work that has gone into this library.

My projects typically involve server side rendering, and support for this functionality within the React community has continued to get better over time. Loading this library on the client side only can work, but it breaks the flow of the app, impacts performance, and reduces our ability to offload processing to the server. In applications where the tables are public facing, this also impacts searchability and No Javascript environments.

I have been working on adding SSR to ReactDataGrid for a while, and I just had to do a major update to my code to fix the Chrome v70 horizontal scrolling issue by merging in your changes. This presented an opportunity to finally do the update properly.

This update works very hard to keep the API identical to the existing implementation. The only major change is that CSS must now be loaded separately as vendor CSS, and this is unfortunately a breaking change.

I am now using this update within my own projects. There is more work to be done on this update (particularly with Test Driven Development), but I wanted to get my first working version into the open source repo to start collaborating more effectively.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

I had difficulty replicating the testing environment within my Ubuntu dev environment.

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
https://github.com/adazzle/react-data-grid/issues/361
https://github.com/adazzle/react-data-grid/issues/542
https://github.com/adazzle/react-data-grid/issues/772
https://github.com/adazzle/react-data-grid/issues/803
https://github.com/adazzle/react-data-grid/issues/993
https://github.com/adazzle/react-data-grid/issues/994
https://github.com/adazzle/react-data-grid/issues/1122

**What is the new behavior?**
The library now supports server side rendering using standard imports.

**Does this PR introduce a breaking change?** (check one with "x")
```
[x] Yes
[ ] No
```

Users need to import css separately from the library. Loading external vendor CSS is common in many popular libraries, and it facilitates bundling in the user's application.

`import 'react-data-grid-addons/dist/react-data-grid-addons.min.css';`

### CODE REVIEW

**Comment by rconard** [comment]
Since this functionality [has](https://github.com/adazzle/react-data-grid/issues/361) [been](https://github.com/adazzle/react-data-grid/issues/542) [requested](https://github.com/adazzle/react-data-grid/issues/772) in [many](https://github.com/adazzle/react-data-grid/issues/803) [previous](https://github.com/adazzle/react-data-grid/issues/993) [issues](https://github.com/adazzle/react-data-grid/issues/994), keeps coming up as an [issue](https://github.com/adazzle/react-data-grid/issues/1122), and was a [proposed](https://github.com/adazzle/react-data-grid/issues/772) feature by @jpdriver , I'm bumping this thread to keep it open.

**Comment by afonsoduarte** [comment]
I'm very keen to help getting this released. @rconard what's stopping this from being merged?

**Comment by statico** [comment]
I would love to see this added. I am trying to use react-data-grid with TypeScript and [community types](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-data-grid), but I can't seem to get TypeScript types if I import the module dynamically as suggested in #994.

**Comment by wpapper** [comment]
I encountered an issue while using react-data-grid with Gatsby (I kept having `gatsby build` fail with a `window is not defined` error since it was generating the static site using Node). Merging this pull request to add server-side rendering would be a massive improvement, and would save hours of debugging for people using react-data-grid with Gatsby.

**Comment by rconard** [comment]
This PR has been marked as **Won't Fix** by the **stale bot**, and I have not gotten any engagement on the PR from the maintainers. I would love to see these commits make it upstream, but I don't have any means of merging without maintainer support.

**Pull request closed without merging**
