### PR TITLE
add request animation frame to prevent resize observer limit loop exception

### PR DESCRIPTION
**Pull request by Karpengold**
Fix for "ResizeObserver loop limit exceeded" inspired by this topic: https://stackoverflow.com/questions/49384120/resizeobserver-loop-limit-exceeded

Related to https://github.com/adazzle/react-data-grid/issues/2712

### CODE REVIEW

**Comment by Karpengold** [comment]
@nstepien @amanmahajan7 hi guys, how do you think is it possible to merge it in order to prevent this error in console?

**Comment by damnitrahul** [comment]
Hey @nstepien @amanmahajan7
Can you guys please merge this? This will stop spamming sentry with issues. 
Thanks!

**Comment by nstepien** [comment]
Could you create a reproducible demo first?
It's probably better to let it crash than have the resize observer trigger re-renders infinitely.

**Comment by soichih** [comment]
This issue "observer limit loop exception" crashes the react-script dev instance so it's highly desirable that this issue is resolved. To reproduce this, you will need sufficiently complex UI so that each resize event takes long time to process (and observer loop will reach its limit).

The PR seems to be conflicting so I've updated to something like this.

```
const resizeObserver = new ResizeObserver(entries => {
    window.requestAnimationFrame(() => {
        if (!Array.isArray(entries) || !entries.length) {
            return;
        }
        const size = entries[0].contentBoxSize[0];
        flushSync(() => {
            setInlineSize(size.inlineSize);
            setBlockSize(size.blockSize);
        });
    });
});
```

I confirm that this patch fixes the issue and react-data-grid becomes usable again.

**Comment by nstepien** [comment]
@soichih Could you please provide a reproducible demo?

**Comment by mikeeus** [comment]
We're seeing this issue as well in a very large application and only on certain browsers. I'm not able to reliably reproduce this on a small demo but its definitely an issue and impacting a significant portion of our users.

**Review by davidjamesfriedman — APPROVED** [review]

**Review by mikeeus — APPROVED** [review]
Fantastic work!

**Review by Gwitchr — APPROVED** [review]

**Review by kcode20 — APPROVED** [review]

**Comment by Karpengold** [comment]
Resolved conflicts in case maintainers would like to merge it :)

**Comment by SarunasMaro** [comment]
I have this issue using the latest code base :) I don't think it was resolved yet

**Pull request closed without merging**
