### PR TITLE
add PropTypes as a separate package

### LINKED ISSUE #744: Getting warnings with react 15.5+
**WHICH VERSION OF REACT ARE YOU USING?**
```
Officially Supported:
[ ] v0.14.x
```

```
Community Supported:
[X] v15.0.x
```

**WHICH BROWSER ARE YOU USING?**

```
Officially Supported:
[X] IE 9 / IE 10 / IE 11
[X] Edge
[X] Chrome
```

```
Should work:
[X] Firefox
[X] Safari
```

--------

**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead see https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
```

**Current behavior**

When you try to run with React 15.5.X you get the following warnings...

```
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.
warning.js:36 Warning: Draggable: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.
```

**Expected/desired behavior**

No warnings

**Reproduction of the problem**

Just use the right version of React

**What is the motivation / use case for changing the behavior?**

React upgrage

Both stack traces show it coming from RDG, I double checked and didn't see any open issues.

### PR DESCRIPTION
**Pull request by suxxes**
Fixes #744

## Description
Because @GlebDolzhikov did not respond since May, I decided to fork, fix, and pull request his original changes for PropType validations.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

With recent React 16 release application does not work with it, because original PropTypes were removed from the core library into a separate.

**What is the new behavior?**

Application uses separate external prop-types library to validate incoming props.

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by jpdriver** [comment]
hey @suxxes -- thank you very much for taking this on. I've been doing some internal testing and we can't merge this in just yet, as it introduces a couple of script errors we don't get on `master`

screen shot 2017-09-28 at 12 07 15 pm

The new `prop-types` package doesn't support validation the way we are currently doing it for certain props on certain components (e.g. [PropTypes.arrayOf()](https://github.com/adazzle/react-data-grid/blob/master/packages/react-data-grid-addons/src/editors/AutoCompleteEditor.js#L16))

The exact components that throw are:-

|Component|Prop|
|----|----|
|AutoCompleteEditor|options
|ReactDataGrid|metricsComputator|
|Grid|metricsComputator|
|Viewport|metricsComputator|

`metricsComputator` will be a difficult one to solve. It's a prop that we're [using as a context type](https://github.com/adazzle/react-data-grid/blob/master/packages/react-data-grid/src/DOMMetrics.js#L4) for a mixin 😰

Mixins have been [considered harmful](https://facebook.github.io/react/blog/2016/07/13/mixins-considered-harmful.html) by the React community for a while now, so potentially this move to `prop-types` will require a wider discussion around migrating away from using mixins as a pre-requisite.

But TL:DR the unfortunate news is I don't think we should merge this until we've gotten rid of those script errors 😞 

cc @malonecj

**Comment by suxxes** [comment]
Hey @jpdriver thanks for hopping in. I will look into those problems too, because I'd love to transition to R16 as soon as possible, and sadly React Data Grid is the only component left that makes me trouble with the transition.

**Comment by jpdriver** [comment]
If you wouldn't mind updating the `AutoCompleteEditor` that would at least be a start 👍 

The mixins stuff has been there since day one (and React 11 😂) so it's probably about time we addressed it

**Comment by giulianf** [comment]
When do you schedule to merge ?

**Comment by suxxes** [comment]
@jpdriver I've fixed all the issues I could find (including docs and examples), all that I see now are that of `metricsComputator`.

**Comment by giulianf** [comment]
Nothing about this PR?

**Comment by IanMarett** [comment]
This PR is the only thing holding back migrating to 16. Any timescales on the merge?

**Comment by suxxes** [comment]
@IanMarett I am sorry, but the whole problem with merging this package and finalizing transition to React 16 is that in latter React.createClass functionality has been deprecated and removed completely. Which forces a decent rewrite of certain functionality of the component to make it work properly, because it uses React.createClass alongside with Mixins.

**Comment by philquinn** [comment]
@suxxes I have a PR with createClass being replaced. #970

**Comment by suxxes** [comment]
@philquinn Awesome! Once it's merged I will merge master into my repo and fix merge issues if any for this PR to go live too. Thank you!

**Comment by malonecj** [comment]
Hi @suxxes, #970 has been merged in so feel free to catch up and resolve conflicts. We will then look to get this merged as soon as possible

**Comment by suxxes** [comment]
Hi @malonecj. Right on to it!

**Comment by dijonkitchen** [comment]
FYI, this fixes #744, so you can add that to your description and auto-close it!

**Comment by suxxes** [comment]
Thank you @dijonkitchen. Added issue info to description.

**Comment by suxxes** [comment]
@malonecj Just in case: I've merged master and PR is ready.

**Comment by tonyleeper** [comment]
Hi, do you have a rough idea of when this might make it into a release? I'm currently working on a React 16 project and I like the look of this grid.  Many thanks!

**Comment by philipbjorge** [comment]
I'm seeing a bunch of the following warnings in the console when running this fork locally.

`Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.`

(Brand new to react, so no idea what this means)

**Comment by malonecj** [comment]
Looks like we are still getting some prop type warnings on example pages. Looks to be from 3rd party libraries  - an old version of React Router. I will merge this in and we can address those in a new PR. Cheers!!

**Comment by Waize** [comment]
still getting warnings in addons:
` propTypes: {
	    /**
	     * A Node, Component instance, or function that returns either. The `container` will have the Portal children
	     * appended to it.
	     */
	    container: _react2.default.PropTypes.oneOfType([_componentOrElement2.default, _react2.default.PropTypes.func])
	  },
`

sorry I can't provide you the right sourcefile.

**Comment by suxxes** [comment]
@Waize I looked through all the files which contain usage of `PropTypes.oneOfType`, all of them have new PropTypes imported. You either forgot to update, or it's something newly added after the migration to external PropTypes.

**Comment by Waize** [comment]
I am using react-data-grid-addons in version 2.0.76

**Comment by john-hadron** [comment]
I get the same error. I think the generated react-data-grid-addons.js was not updated?

file:package.json
```package.json
    "react-data-grid": "^2.0.78",
    "react-data-grid-addons": "^2.0.78",
```

file: node_modules/react-data-grid-addons/dist/react-data-grid-addons.js
```js
var Modal = _react2.default.createClass({
	  displayName: 'Modal',


	  propTypes: _extends({}, _Portal2.default.propTypes, {

	    /**
	     * Set the visibility of the Modal
	     */
	    show: _react2.default.PropTypes.bool,

	    /**
	     * A Node, Component instance, or function that returns either. The Modal is appended to it's container element.
	     *
	     * For the sake of assistive technologies, the container should usually be the document body, so that the rest of the
	     * page content can be placed behind a virtual backdrop as well as a visual one.
	     */
	    container: _react2.default.PropTypes.oneOfType([_componentOrElement2.default, _react2.default.PropTypes.func]),
...
```

file: node_modules/react-data-grid-addons/package.json
```json
{
  "name": "react-data-grid-addons",
  "version": "2.0.78",
  "description": "A set of addons for react-data-grid",
  "scripts": {
    "beforepublish": "node ../../ci/publish/replacePackageEntry react-data-grid-addons true",
    "postpublish": "node ../../ci/publish/replacePackageEntry react-data-grid-addons",
    "test": "npm test"
  },
  "keywords": [
    "react",
    "react-data-grid",
    "react-data-grid-addons"
  ],
  "author": "Adazzle",
  "license": "MIT",
  "dependencies": {
    "react-data-grid": "^2.0.78"
  },
  "devDependencies": {
    "jquery": "^2.1.1",
    "lodash": "^4.13.1",
    "lodash.groupby": "^4.5.1"
  }
}
```

**Comment by 29er** [comment]
what's the status of this ? I am getting the same errors and starting to realize I can't use this grid anymore :(

**Comment by rkram5424** [comment]
I too am having an issue with `'oneOfType' of undefined` originating from react-data-grid-addons. Is anyone working on this? It would be nice to use it with react 16.

**Comment by charleyw** [comment]
> I too am having an issue with 'oneOfType' of undefined originating from react-data-grid-addons. Is anyone working on this? It would be nice to use it with react 16.
I have the same issue, and after a short investigation. I found it is caused by one of the dependency of contextMenu in react-data-grid-addon.
https://github.com/adazzle/react-data-grid/blob/master/package.json#L36
> "react-contextmenu": "1.6.2",
`react-contextmenu@1.6.2` depends on `react-overlays@^0.6.3`, and `react-overlays@^0.6.3` is using old proptype.

**Comment by utajum** [comment]
There is an ongoing pull request https://github.com/adazzle/react-data-grid/pull/1081#issuecomment-362081696

**Pull request merged**
