### PR TITLE
rm Cell export and RowRendererProps.cellRenderer

### PR DESCRIPTION
**Pull request by nstepien**
I'm not 100% sure we should do it, but we don't use it ourselves, and it's better than abusing custom renderers just to add class names.
We can revert this in any case.

### CODE REVIEW

**Review by amanmahajan7 — APPROVED** [review]
We can add it back if needed
https://github.com/adazzle/react-data-grid/issues?q=is%3Aissue+cellrenderer+is%3Aclosed

**Comment by mmasdivins** [comment]
If we want to add a custom classname to an specific cell how we can do it now that we don't have the property cellRenderer?

**Comment by mmasdivins** [comment]
But that will be for all the cells of that column and I want to do it for a specific cell in a row

**Comment by nstepien** [comment]
```js
Column.cellClass = (row) => ...
```

**Comment by mmasdivins** [comment]
Thanks

**Comment by amber-cd** [comment]
We're working on upgrading to v7 and we use the CellRenderer fairly extensively in order to display a variety of different custom components depending on the column in question. It's more extensive than just adding a class. What is the new way to do this, if CellRenderer has been removed?

**Pull request merged**
