### PR TITLE
:new: Implement initialScrollTop and initialScrollLeft

### PR DESCRIPTION
**Pull request by ekeuus**
This PR implements a way to restore scroll of a Grid on mount when the previous scroll values have been stored somewhere - redux, a context somewhere, localstorage, etc.

I also added a story where you can scroll around down and right, look at another story and upon returning to the "Initial scroll" demo, the original scroll is restored during the initial mount.

### CODE REVIEW

**Comment by ekeuus** [comment]
@nstepien @amanmahajan7 Let me know if this makes sense or not. IMO it is a very small change and should not break anything for existing users. However, it is a much needed use case and would be the best if it was in the library already instead of re-implementing it.

**Comment by nstepien** [comment]
IMO that's something that can and should be done outside the component.

**Comment by nstepien** [comment]
Considering you have access to the root via `ref=(obj => obj.element}`, this should be implemented as needed, instead being a built-in function. WDYT @amanmahajan7?

**Comment by amanmahajan7** [comment]
I agree with @nstepien, we can use [gridRef ](https://github.com/adazzle/react-data-grid/blob/main/src/DataGrid.tsx#L370)to handle it outside the grid.

**Pull request closed without merging**
