### PR TITLE
Migrate from Webpack to Vite

### PR DESCRIPTION
**Pull request by amanmahajan7**

### CODE REVIEW

**Comment by amanmahajan7** [comment]
Blocked on https://github.com/vitejs/vite/issues/11035

**Comment by godon019** [comment]
I would like to know better on this. what is the challenge on migrating to Vite outside of linaria?

**Comment by nstepien** [comment]
@godon019 Linaria is the only thing causing trouble really, otherwise it works very well afaict, especially with Vite 4.3.

**Comment by nstepien** [comment]
@amanmahajan7 Let's :shipit: 
After this we can try Vitest without browser testing, then maybe rollup later.

I reverted the rollup changes to be safe, I want to see how it'd affect the output.
Vite is based on rollup anyway, and rollup has been working very well for us so not a huge priority.

**Review by nstepien — APPROVED** [review]

**Review by amanmahajan7 — COMMENTED** [review]
Looks great

**Comment by amanmahajan7** [comment]
hmm, `npm run preview` does not work

**Comment by amanmahajan7** [comment]
> hmm, npm run preview does not work

Actually it does :)

**Comment by nstepien** [comment]
Looks like we need to tweak the output to fix the paths in gh pages.

**Comment by nstepien** [comment]
I've pushed a fix straight to `main`: https://github.com/adazzle/react-data-grid/commit/2df400b42929334f6464c57b72e71d44cf87c713
The [website](https://adazzle.github.io/react-data-grid/#/common-features) is now working again, and on esm!

**Pull request merged**
