### PR TITLE
Pass props to custom sortable header renderer

### PR DESCRIPTION
**Pull request by klacointe**
## Description
A few sentences describing the overall goals of the pull request's commits.

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[X] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
headerRenderer for sortable header column have no props.
https://github.com/adazzle/react-data-grid/issues/804

**What is the new behavior?**
headerRenderer for sortable header column have sortDirection and sortDir props

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[X] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by jstray** [comment]
Running into this problem right now and would love to see this small change integrated.

**Comment by harry-tc-zhang** [comment]
+1. This would be a really handy feature and make custom header renderers much more useful.

**Comment by jstray** [comment]
Please merge this PR.  It's a small change and  we have to work around this on our current project.

**Comment by anucreative** [comment]
Would also really like to see this merged. :)

**Comment by malonecj** [comment]
Hi guys. Thanks for the submission and apologies for the delay to get it merged

**Pull request merged**
