### PR TITLE
Remove isLastFrozenColumn in favor of the new has selector

### PR DESCRIPTION
**Pull request by amanmahajan7**
https://webkit.org/blog/13096/css-has-pseudo-class/
https://caniuse.com/css-has

We can merge it when the browser support is good.

### CODE REVIEW

**Comment by amanmahajan7** [comment]
Not sure why the build is failing

**Comment by nstepien** [comment]
https://github.com/callstack/linaria/issues/1054

**Comment by amanmahajan7** [comment]
Accidently requested review

**Comment by amanmahajan7** [comment]
It is probably better to have extra classes for easy customization.

**Pull request closed without merging**
