### PR TITLE
Multiple columns sort implementation

### PR DESCRIPTION
**Pull request by bhunjadi**
## Description
A few sentences describing the overall goals of the pull request's commits.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
There is only support for single column sorting.

**What is the new behavior?**
Added possibility for multi column sorting with property `multipleColumnsSort` on `ReactDataGrid` component.
Sort callback function for multiple sort is `onGridMultipleColumnsSort` instead of `onGridSort` which is still used for single column sort.
Additionally, there is possibility to pass initial sort with `sort` property.

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

**Other information**:
Related to #491

### CODE REVIEW

**Comment by joinsunil** [comment]
Any update on this ? How can I sort multiple columns in table ?

**Comment by laaglu** [comment]
@bhunjadi Are you still working on this feature ? I am myself also interested in it and could submit a PR for it if you have decided to work on something else

**Comment by bhunjadi** [comment]
@laaglu I am using my forked version which seems to be working fine. I see that there are some conflicts now, I'll try to resolve them in next few days.

**Comment by oysmal** [comment]
Is this pull-request going to get approved in the near future? We are using the component at my company and do not wish to implement this ourselves if it is going to be added soon. If it is not, can we do anything to help finish the feature to a satisfying degree for the maintainer(s) to merge it?

**Comment by bhunjadi** [comment]
I am, too, interested in what is stopping this to be merged and prepared to make the necessary changes. I've been using my forked version for quite a while now, but it is not that convenient.
As of latest commit, even tests have been added for this feature.

Something for discussion (probably) before merge:
- `onGridMultipleColumnsSort` - do we use that callback (to denote the difference between single and multiple column sort) or should the same callback be used (`onGridSort`)?

**Comment by oysmal** [comment]
Is there any new status on this?

**Comment by bhunjadi** [comment]
@aznikht no reason I can think of, maybe just not enough people interested in this feature

**Comment by shridharbennisur** [comment]
@bhunjadi , please can you provide your forked version package.

**Comment by shridharbennisur** [comment]
@bhunjadi , please can you provide your forked version package.

**Comment by shridharbennisur** [comment]
@bhunjadi , please can you provide your forked version package.

**Comment by shridharbennisur** [comment]
@bhunjadi , please can you provide your forked version package.

**Comment by shridharbennisur** [comment]
@bhunjadi , I am interested in this feature can you provide your forked version package.

**Comment by shridharbennisur** [comment]
@bhunjadi , I am interested in this feature can you provide your forked version package.

**Comment by shridharbennisur** [comment]
@bhunjadi , I am interested in this feature can you provide your forked version package.

**Comment by shridharbennisur** [comment]
@bhunjadi , I am interested in this feature can you provide your forked version package.

**Comment by shridharbennisur** [comment]
@bhunjadi , can you provide your working snippet for multiple sorting

**Comment by bhunjadi** [comment]
You can check this [example](https://github.com/adazzle/react-data-grid/pull/955/files#diff-45c7a11d82b7cf0d05e02b63d70b749d)

Important part...
```
<ReactDataGrid
        onGridMultipleColumnsSort={this.handleSort}
        multipleColumnsSort={true}
       ...
/>
```

and then in `handleSort` you'll get an array.

**Comment by shridharbennisur** [comment]
@bhunjadi Thanks a lot

**Comment by shridharbennisur** [comment]
@bhunjadi , on row-click I am getting error has Uncaught TypeError: Cannot read property '_warnedAboutRefsInRender' of null 
at Canvas._this.getSelectedRowHeight (react-data-grid.js:4095)

**Comment by bhunjadi** [comment]
@shridharbennisur 
I'm not sure if this is caused by multiple sort. Have you tried it with single sort?

**Comment by madanagopal** [comment]
Any Update on this.? I am interested in Multiple Sort as well.

**Comment by Butzman** [comment]
Any Update?

**Comment by bhunjadi** [comment]
I can sync my fork if it will be merged.

**Comment by ubreddy** [comment]
@joinsunil who is looking at merging this PR?

**Pull request closed without merging**
