### PR TITLE
:new: Add onRowChange method for a single row change

### PR DESCRIPTION
**Pull request by ekeuus**

### CODE REVIEW

**Comment by ekeuus** [comment]
@nstepien Do you think this kind of an api would make sense? Not all users need/want the whole grid data out directly

**Comment by nstepien** [comment]
We're thinking about doing something like
```js
onRowsChange(updatedRows, {
  indexes: [rowIdx], // will contain 1 or more indexes of the rows that have been updated
  column: column // column that has been updated/triggered an update on the rows
});
```
Would that work for you?

**Comment by ekeuus** [comment]
> We're thinking about doing something like
> 
> ```js
> onRowsChange(updatedRows, {
>   indexes: [rowIdx], // will contain 1 or more indexes of the rows that have been updated
>   column: column // column that has been updated/triggered an update on the rows
> });
> ```
> 
> Would that work for you?

Yeah, that's even better since then we I can also detect which field I need to update instead of the whole row :)

**Comment by ekeuus** [comment]
Should I implement it myself or is someone else already looking at it?

**Comment by nstepien** [comment]
We'll look into it, probably tomorrow.

**Pull request closed without merging**
