### PR TITLE
[BUGFIX] minColumnWidth fix 

### PR DESCRIPTION
**Pull request by martinnov92**
## Description

Hello everyone,

in this pull request I tried to fix this weird behavior of not respecting minColumnWidth when resizing the window or grid. 
Current situation is when you are resizing the window, all the columns are calculating its width and don't respect their set minColumnWidth which may cause that they become really small (here is the [video](https://drive.google.com/open?id=0B04DA-ziLi_GRm5fTmsycjI2emc)), but after this fix, once their width become less then minColumnWidth, they keep the minColumnWidth - [video](https://drive.google.com/open?id=0B04DA-ziLi_GT0pnV1ZZeC11WGs) 

Hopefully I am not the only one who would appreciated this fix 😄 .

Thank you

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

Current situation is when you are resizing the window, all the columns are calculating its width and don't respect their set minColumnWidth which may cause that they become really small (here is the [video](https://drive.google.com/open?id=0B04DA-ziLi_GRm5fTmsycjI2emc))

**What is the new behavior?**

After this fix, once their width become less then minColumnWidth, they keep the minColumnWidth - [video](https://drive.google.com/open?id=0B04DA-ziLi_GT0pnV1ZZeC11WGs) 

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by martinnov92** [comment]
Hello @jpdriver , do you mind making a code review for me? :) thank you

**Comment by martinnov92** [comment]
Hello @jpdriver and @malonecj  , do you mind making a code review? thank you

**Comment by jpdriver** [comment]
this looks good to me.. @malonecj please can you merge?

**Comment by jpdriver** [comment]
ps thank you so much for the videos @martinnov92 -- if only all PRs had them! 😛

**Comment by martinnov92** [comment]
@jpdriver  Thank you too :)

**Comment by martinnov92** [comment]
Hello @malonecj and @jpdriver , do you think this will get merge anytime soon? thank you

**Comment by jpdriver** [comment]
would have already merged this if i could @martinnov92 ! unfortunately i can't help -- you'll just have to wait until Conor has time to look at it.

**Comment by martinnov92** [comment]
@jpdriver Ok, thank you :)

**Comment by mitchelldemler** [comment]
Bump. This is pretty crucial for a responsive table.

**Comment by martinnov92** [comment]
@mitchelldemler I know, right? It is pretty annoying that we can't properly resize columns :/

**Pull request merged**
