### PR TITLE
Allow for optional SimpleCellFormatter.value prop (#326)

### PR DESCRIPTION
**Pull request by chuntley**
## Description
Passing in null to SimpleCellFormatter is valid, this PR removes the `isRequired` flag on propTypes to remove warnings from the console when null is passed as a value.

**What kind of change does this PR introduce?** (check one with "x")
```
[X] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
Prop type warning is thrown when a null value is passed to SimpleCellFormatter

**What is the new behavior?**
No warning is thrown

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[X] No
```

**Other information**:

Fixes: https://github.com/adazzle/react-data-grid/issues/326 using michielboekhoff's suggestion in the thread.

### CODE REVIEW

**Comment by dklanac** [comment]
For those like me who are waiting for this to be merged into `master`, here's a quick way to incorporate @chuntley 's PR now as a temporary monkey patch:

Just pop this into your codebase and make sure that it's called after you've loaded up `ReactDataGrid`.

You can verify that the warning 

>  Warning: Failed prop type: The prop `value` is marked as required in `SimpleCellFormatter`,

No longer displays in your console. 

```
const SimpleCellFormatter = ReactDataGrid.formatters.SimpleCellFormatter

SimpleCellFormatter.propTypes = {
  value: React.PropTypes.oneOfType(
    [
      React.PropTypes.string, 
      React.PropTypes.number,
      React.PropTypes.object,
      React.PropTypes.bool
    ]
  )
}
```

**Comment by chuntley** [comment]
Anything else needed to get this merged in?

**Comment by amanmahajan7** [comment]
@chuntley thank you for the PR. This will be released in the next minor release

**Pull request merged**
