### PR TITLE
PR for Issues (https://github.com/adazzle/react-data-grid/issues/1441, https://github.com/adazzle/react-data-grid/issues/1442, https://github.com/adazzle/react-data-grid/issues/1400, https://github.com/adazzle/react-data-grid/issues/1181, https://github.com/adazzle/react-data-grid/issues/1443)

### PR DESCRIPTION
**Pull request by madhan-dhamodaran**
## Description
A few sentences describing the overall goals of the pull request's commits.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ X] Feature
[ ] Code style update (formatting, local variables)
[ X] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)

**What is the new behavior?**

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[ ] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by madhan-dhamodaran** [comment]
I will be working on resolving the conflicts and meeting the other requirements.

Thanks,
Madhan

**Comment by madhan-dhamodaran** [comment]
@amanmahajan7 @jlbooker @Jcholerton-Adazzle ,

Hi All, this is a major change and I have introduced a lot of features to the grid. Please have a review and let me know if you have any comments. 

Thanks,
Madhan

**Comment by madhan-dhamodaran** [comment]
@amanmahajan7 @jlbooker @Jcholerton-Adazzle , @alefherrera @tenpaiyomi @azu @maiis @txm @LittleBoxOfSunshine , Was anyone able to look into this PR pls.

**Comment by richardware** [comment]
Hi @madhan-dhamodaran,

Sorry you haven't yet had any feedback on this.

It all looks interesting, but it's very difficult to review in the current format - is there a reason why this couldn't be split in to one PR per issue?

**Comment by madhan-dhamodaran** [comment]
hi @richardware ,

Sorry for the late reply. This is worked for almost the whole last year and I incorrectly created a branch out from my fork and had individuals PRs raised and realized they were going to be merged only to my fork. So, when I merged it, everything just formed a huge change list. So here we are now. However, I have introduced a lot of features to the grid. So, if someone could review this and take it to next step, it will be really helpful. Sorry again for the huge number of changes in just one PR. Kindly do the needful.

Thanks,
Madhan

**Comment by l-wagner** [comment]
To show some user interest: The typeahead filter, the tooltip headers and the react-select upgrade are features/improvements that would make my life a lot easier. I understand that it's a vast amount of changes to review, but I'd very much appreciate it. :)

**Comment by madhan-dhamodaran** [comment]
@amanmahajan7 @jlbooker @Jcholerton-Adazzle , @alefherrera @tenpaiyomi @azu @maiis @txm @LittleBoxOfSunshine @richardware , Hey guys, was anyone able to look in to this? 

Kindly advise. 

Thanks,
Madhan

**Comment by amanmahajan7** [comment]
Hi @madhan-dhamodaran thank you so much for the PR and apologizes for the late reply. Unfortunately this PR cannot be reviewed in its current state and we need to break it down into separate PRs so things can be reverted/fixed in isolation. 

We are also considering retiring some of the existing addons and instead focus on making RDG more flexible so users can customize it however they like. There are a few reasons behind this decision 
- Addons are not actively maintained
- It is impossible to handle every use case


https://github.com/adazzle/react-data-grid/issues/1441 `Typeahead Filter` is great but as I mentioned previously it will be hard to address every use case. I would recommend adding this filter to a new repository and publish it separately

https://github.com/adazzle/react-data-grid/issues/1442 `Add/Remove Columns` another great feature but I think it does not need to part of core RDG repository

https://github.com/adazzle/react-data-grid/issues/1181 - Same reasoning

https://github.com/adazzle/react-data-grid/issues/1400 - Will accept PR

https://github.com/adazzle/react-data-grid/issues/1443 - `set default filtering values in filter text boxes` Will accept PR

Thank you again

**Comment by dsadaka** [comment]
Hello everyone.  I am tasked with adding saved filters from cookies.  I read about PR 1443 and it looks like exactly what I need.  I see from above that it was accepted but, as of this writing, is still open.  We're about to upgrade the grid to the latest version and are looking forward to this feature (along with the fix to the checkbox column when filtering).

Can anyone please provide a status for 1443?

**Comment by BlaineBradbury** [comment]
@amanmahajan7 are you able to review this one?  Especially for the #1400 bug.

**Comment by starkysclub** [comment]
Hey guys I separated the #1400 bug to a new pull request, so it can get merged more quickly, can you look into it?

**Comment by amanmahajan7** [comment]
Closing this PR as we have decided to keep the react-grid-code slim so all the filters/editors should be implemented externally. 

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos

**Pull request closed without merging**
