### PR TITLE
Fix for Browserify without babelify

### PR DESCRIPTION
**Pull request by bradleat**
Since you are building to the esnext standard, some builders (browserify) are unable to build your code into a bundle without help or special configuration. 

This simple change allows more people to run your package without problems.

Also, we use the `--experimental-modules ` flag so more versions of node can run your `buildStylesheets.mjs` script.

### CODE REVIEW

**Comment by bradleat** [comment]
@qili26 can you let me know who can review this

right now your npm package doesn't work for some because of the build rules you are using. this set of build rules opens it up to more targets

**Comment by bradleat** [comment]
@amanmahajan7

@nstepien

**Comment by nstepien** [comment]
It looks like you should be able to configure babelify to transform esm into cjs.
https://github.com/browserify/browserify/issues/1186#issuecomment-572119852

**Comment by bradleat** [comment]
@nstepien 
I've tried babelify doesn't work because it breaks other well known packages. What's the problem with exporting the commonjs style modules until the esnext ecosystem is more mature?

**Comment by nstepien** [comment]
https://github.com/babel/babelify#why-arent-files-in-node_modules-being-transformed
Looks like this config should work for you.
```js
browserify().transform("babelify", {
  global: true,
  ignore: /\/node_modules\/(?!react-data-grid\/lib\/)/
});
```

Modern bundlers like rollup/webpack/etc have great support for es modules. We can reconsider publishing additional cjs modules if there's really a need for it.

**Comment by bradleat** [comment]
Seeing as browserify is the second most downloaded bundler according to npm, I imagine there is a need for it. As for my needs: I've published a package with these changes.

Browserify will have better support for mjs soon, until then I don't understand the benefit you are getting for chasing the bleeding edge before the standard is actually set.

**Comment by nstepien** [comment]
@bradleat 
We publish both esm and cjs modules now, targeting the [latest browsers and maintained Node.js versions](https://github.com/adazzle/react-data-grid/blob/main/browserslist), can you confirm if this bundling with browserify is still an issue?

**Pull request closed without merging**
