### PR TITLE
DropDownEditor to accept a similar data structure as AutoCompleteEditor

### PR DESCRIPTION
**Pull request by txm**
var priorities = [{id:0, value : 'Critical'}, {id:1, value : 'High'}, {id:2, value : 'Medium'}, {id:3, value : 'Low'}]
Note/for discussion: where 'title' is reserved for html5/bootstrap tooltip

### CODE REVIEW

**Comment by malonecj** [comment]
Hi, thanks for the pull request, looks good to me. Would you be able to resolve the conflicts from master so we can merge

**Comment by txm** [comment]
I don't know what makes this PR 'non-mergeable', what am I missing?

**Comment by diogofcunha** [comment]
Hi,
The are some conflicts in 
> src/addons/editors/DropDownEditor.js

If you use the command line to resolve the conflicts it will be straight forward.

**Comment by diogofcunha** [comment]
I have noticed a few important things about your fork on react-data-grid.

You are running an old version of react-data-grid, I can dig out a few problems that may happen in every pull request.

1. **Eslint** 
-
 - **Rules**: A gulp task was created to break the build event when the code in src folder doesn't respect the rules defined in [eslint configuration file](https://github.com/adazzle/react-data-grid/blob/master/.eslintrc).

- **Tools**: To know where you break the rules, there are some good packages and extensions available, for atom you can use [linter-eslint](https://github.com/AtomLinter/linter-eslint), for visual studio code you can use [vscode-eslint](https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint).

2. **React**
-
-  We are now running react 14 while your fork still on react 13  Some react 13 features have been deprecated in the new version.

3. Other
-  
- To respect all the rules in eslint configuration some files and folders needed a big change and it is very likely that future pull requests will end in conflict with our master.

I advice you to upgrade your fork to our latest version as soon as possible.

**Pull request closed without merging**
