### PR TITLE
Removed string refs.

### PR DESCRIPTION
**Pull request by michielboekhoff**
## Description
A few sentences describing the overall goals of the pull request's commits.

**Please check if the PR fulfills these requirements**
- [ X ] The commit message follows our guidelines: https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
- [ X ] Tests for the changes have been added (for bug fixes / features)
- [ X ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ X ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
Currently, the deprecated string refs are being used in the codebase. This causes newer installs of React to choke and to throw an error.

**What is the new behavior?**
I've removed all string refs (to the best of my knowledge!) and replaced them with functions. The tests are still passing, and the examples seem to be running with fewer errors now.

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[ X ] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
I hope this covers all of the string refs. If not, please tell me where I missed one, and I'll fix it.

### CODE REVIEW

**Comment by michael-iglesias** [comment]
Any idea when this is going to be merged in?

Thanks,
Michael

**Comment by michielboekhoff** [comment]
@michael-iglesias I've not heard from the team yet. I've merged it to master on my own fork, as we needed it ASAP. If you need it, you could find the fix there.

**Comment by malonecj** [comment]
Hi 
Thanks for the PR. This will be very useful. I have just done some regression testing on this branch. It looks like horizontal scrolling is broken. The headers do not scroll with the grid

Please see the video of the bug
https://www.useloom.com/share/3203d34fda6d425ca4956dfe5fb46c4a

**Comment by michielboekhoff** [comment]
@malonecj You're right, I'll have a look at that later today.

**Comment by michielboekhoff** [comment]
@malonecj I've found the error and tested that this regression no longer occurs. The problem was a missing `ReactDOM.findDOMNode`, but I've added it back in and it should work now.

**Comment by michielboekhoff** [comment]
Whoops, accidentally forgot to uncomment the require. Fixed. Tests should pass now.

**Comment by malonecj** [comment]
Great, thank you very much. Have checked that's all working now. Looks good to merge

**Comment by michael-iglesias** [comment]
Thanks @michielboekhoff  @malonecj

**Pull request merged**
