### PR TITLE
React 14 upgrade

### PR DESCRIPTION
**Pull request by malonecj**

### CODE REVIEW

**Comment by luin** [comment]
Any issue here keeping this pr from being merged?

**Comment by malonecj** [comment]
I need to schedule some time to work on this. And get a few of the examples working correctly

**Comment by omarish** [comment]
Anything I can do to help here?

**Comment by jnelsonforsythe** [comment]
Any update for when this will get merged? We really want to use your data grid but we are using React v0.14.3.

**Comment by n8gard** [comment]
Not trying to spam, but really hoping this gets merged in asap. Is it ill-advised to couple to the feature-branch? Otherwise I have to go with a different grid that I don't like as much as this one.

**Comment by malonecj** [comment]
sorry for the confusion but this work needs to be started from scratch. The commits above correspond to work done in the upgrade to React 13. And no work has been done yet on upgrade to React 14. I had hoped to start this a while ago but have not had time. Unless anyone else can pick this up, I dont see this getting completed till early - mid Jan

**Pull request closed without merging**
