### PR TITLE
Add completion flag for column resize callback

### PR DESCRIPTION
**Pull request by sergeyt**
Extended `onColumnResize` to have completion flag. It is useful when you need to save changes on the server.

---
This change is [Reviewable](https://reviewable.io/reviews/adazzle/react-data-grid/2072)

### CODE REVIEW

**Comment by amanmahajan7** [comment]
@sergeyt thanks for the PR and apologies it took so long to get back to you. Can you resolve the conflicts and we can review and merge it,

**Comment by gernotkogler** [comment]
Why not use a new callback `onColumnResized`?

**Comment by amanmahajan7** [comment]
@sergeyt can you please resolve the conflicts?

**Comment by amanmahajan7** [comment]
Closing due to lack of response

**Pull request closed without merging**
