### PR TITLE
Use row overscan prop

### LINKED ISSUE #1683: Overscan property has no effect on row rendering
- Have you already searched for similar issues? Please help us out and double-check first!
I created an issue a few months ago, but it went stale and was closed. I can't re-open it myself, so I'm making a new one to link to a PR.

- Also, please don't be that person who deletes this template. It's here for a reason.

- Thanks!

---

### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [x] v15.5.x
- [ ] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details
The overScan prop is passed down to the Viewport, but nothing uses it. It seems like it should be used in utils/viewportUtils, but instead a const, OVERSCAN_ROWS (== 2) is used.
All columns are always rendered, so overscan is not applicable in that case.
But the row rendering should use the overscan prop.

```
Please include:
- What the current behavior is
- What the desired behvaior is
- (If Bug) Steps to reproduce the issue
- (If Feature) The motivation / use case for the feature

We especially love screenshots / videos of problems, and remember
The Best Issue Is A Pull Request™
```

### PR DESCRIPTION
**Pull request by zekehernandez**
## Description
Fixes #1683 
The overscan prop is now used for row rendering.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
#1683 

**What is the new behavior?**
The overscan prop is now used for row rendering.

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by zocheyado** [comment]
Is this live / getting merged anytime soon? Causing issues on Master for me.

**Comment by pellejacobs** [comment]
@amanmahajan7 @nstepien Could you guys have a look at this? It'd be great to be able to manage the virtualisation behaviour a bit better. Eg. blocks issues like https://github.com/adazzle/react-data-grid/issues/915. Thanks!

**Comment by mlmassey** [comment]
If anyone is looking for a solution to this, you can add this monkey patch code.  Tested on React Data Grid 5.0.4 (does not apply to the newer 6/7/canary).  This assumes you pass in the ref provided by the ReactDataGrid when mounting it.

```javascript
const OVERSCAN_ROWS = 20;

function getRowOverscanStartIdx(scrollDirection, rowVisibleStartIdx) {  const result = rowVisibleStartIdx - OVERSCAN_ROWS;
  return result < 0 ? 0 : result;
  /* The code below comes from the react-data-grid implementation, but used my implementation above to increase overscan size
  return scrollDirection === 'upwards'
    ? Math.max(0, rowVisibleStartIdx - OVERSCAN_ROWS)
    : Math.max(0, rowVisibleStartIdx);
  */
}

function getRowOverscanEndIdx(scrollDirection, rowVisibleEndIdx, rowsCount) {
  const overscanBoundaryIdx = rowVisibleEndIdx + OVERSCAN_ROWS;
  return overscanBoundaryIdx > rowsCount ? rowsCount : overscanBoundaryIdx;
  /* The code below comes from the react-data-grid implementation, but used my own code to increase overscan size
  return scrollDirection === 'downwards'
    ? Math.min(overscanBoundaryIdx, rowsCount)
    : rowVisibleEndIdx;
  */
    function monkeyPatchGetNextScrollState(ref) {
    if (!OVERSCAN_ROWS) {
      return;
    }
    if (ref.base && ref.base.viewport && ref.base.viewport.getNextScrollState) {
      let oldGetNextScrollState = ref.base.viewport.getNextScrollState;
      oldGetNextScrollState = oldGetNextScrollState.bind(ref.base.viewport);
      ref.base.viewport.getNextScrollState = arg => {
        if (typeof arg !== 'object' || typeof arg.rowsCount !== 'number') {
          throw new Error('getNextScrollState unexpected argument');
        }
        const result = oldGetNextScrollState(arg);
        if (
          typeof result !== 'object' ||
          result.scrollDirection === undefined ||
          result.rowOverscanStartIdx === undefined ||
          result.rowOverscanEndIdx === undefined
        ) {
          throw new Error('getNextScrollState unexpected result');
        }
        result.rowOverscanStartIdx = getRowOverscanStartIdx(
          result.scrollDirection,
          result.rowVisibleStartIdx
        );
        result.rowOverscanEndIdx = getRowOverscanEndIdx(
          result.scrollDirection,
          result.rowVisibleEndIdx,
          arg.rowsCount
        );
        return result;
      };
    } else {
      throw new Error('Unable to apply getNextScrollState patch');
    }
  }
}

```

**Comment by amanmahajan7** [comment]
Closing this PR as old version of rdg are no longer supported and this prop is removed in canary 

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos

**Pull request closed without merging**
