### PR TITLE
Compute viewportColumns only once in DataGrid

### PR DESCRIPTION
**Pull request by MayhemYDG**

### CODE REVIEW

**Comment by qili26** [comment]
@amanmahajan7 IMHO Lerna PR seems way too big now that we might want to merge it asap.

**Comment by MayhemYDG** [comment]
I've split computing `viewportColumns` into a separate `useMemo`, so we don't end up with a new array on each `scrollLeft` change, that should prevent unnecessary memoized component re-renders.

**Comment by qili26** [comment]
@MayhemYDG Do we really need to separate it? Whenever `columnMetrics` changes, they both changes, the the new added `useMemo` is using the result of the previous memo result, so they will always change together, won't they?

**Comment by MayhemYDG** [comment]
>Whenever `columnMetrics` changes, they both changes

Yes, that's how it should be. `columnMetrics` shouldn't change often though, check its `useMemo` dependencies.

>the new added `useMemo` is using the result of the previous memo result, so they will always change together, won't they?

Yes and no, `horizontalRange` will always change on `scrollLeft` change for example, but `horizontalRange.colOverscanEndIdx` and `horizontalRange.colOverscanStartIdx` on the other hand won't always change on `scrollLeft` change. Again, check the dependencies used for `useMemo`.

**Pull request merged**
