### PR TITLE
[canary.13] Draggable container without drag drop context

### PR DESCRIPTION
**Pull request by jwallet**
## Description
Added along with the default DraggableContainer, one draggableContainer that does not have the dndContext

```javascript
import { DraggableHeader } from 'react-data-grid-addons';

// need to have  <DragDropContextProvider backend={HTML5Backend}><App ... /></DragDropContextProvider>
const { DraggableContainerWithoutDragDropContext: DraggableContainer } = DraggableHeader;
// or the usual way
const { DraggableContainer } = DraggableHeader
```

i know that's not a priority to make addons work on `canary` but i try to keep my custom DataGrid up to date with your canary release and without this thing we have to use the forked repo.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/adazzle/react-data-grid/blob/master/docs/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
I and others #1482 #863 #1195 have already an instance of html5backend in their project resulting in an error
> Cannot have two HTML5 backends at the same time.

**What is the new behavior?**
 i'm suggesting to export a const along with the default and untouched DraggableContainer, DraggableContainerWithoutDragDropContext

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:
Let me know if the additions to the `.gitignore` are fine, I had trouble switch repo from canary.6 to canary.13, I had node_modules, dist, lib in many deleted repo, that actually broke my GitKraken UI, it frozed. About +16,000 files that were in my stash.

### CODE REVIEW

**Comment by jwallet** [comment]
@nicoder it will great to have this reviewed to be able to don't use the fork anymore and follow your canary releases, we already use react-dnd for attachments module and this is causing a huge bug atm

**Comment by nicoder** [comment]
hi @jwallet

are you sure you meant to tag me ?

**Comment by jwallet** [comment]
oups, i looked at the github tree lines, who was making canary release and saw nicolas stepien, so i tag the wrong one @nstepien

**Comment by nstepien** [comment]
As you may have noticed, we've removed the rdg-addons package, as we're trying to keep a leaner core, and the addons were more maintenance work than we could handle. What we suggest to do is to copy over the addons you need over to your own repo, or to completely replace them.

**Comment by amanmahajan7** [comment]
Closing this PR as old version of rdg are no longer supported and these components have been removed in canary

https://github.com/adazzle/react-data-grid/blob/canary/CHANGELOG.md
https://adazzle.github.io/react-data-grid/canary/?path=/story/demos--common-features
https://github.com/adazzle/react-data-grid/tree/canary/stories/demos

**Pull request closed without merging**
