### PR TITLE
Abillity to freeze columns to the right

### PR DESCRIPTION
**Pull request by Matangub**
#2873. I added a frozen column example to the common features demo

### CODE REVIEW

**Comment by amanmahajan7** [comment]
This does not handle keyboard navigation and virtualization so this PR cannot be expected in the current state. We probably need to change `frozen` field to `'left' | 'right'`.

**Comment by Hideer** [comment]
@amanmahajan7 When can I use it? `frozen` to `'left' | 'right'`

**Comment by matanAlltra** [comment]
> @amanmahajan7 When can I use it? `frozen` to `'left' | 'right'`

You need to add a column with the frozen column key it does not use the frozen property

**Comment by lucasalmeida92** [comment]
Any updates on that?

**Comment by manojkumarboppisetti** [comment]
hey @amanmahajan7 any update on this? when this feature can be expected to freeze right columns 👀

**Comment by merabtenei** [comment]
Any update on this in 2024 ?

**Comment by nqsjd178559344** [comment]
Any update on this in 2024 ?

**Comment by zuizeze** [comment]
@amanmahajan7 Any progress on this feature ?

**Comment by iamrakhmatov** [comment]
@amanmahajan7 any updates on this one?

**Comment by amirmn72** [comment]
Are there any updates on this? This feature has been requested for three years!

**Pull request closed without merging**
