### PR TITLE
add PropTypes as a separate package

### PR DESCRIPTION
**Pull request by GlebDolzhikov**
## Description
Attempt to to get rid of warnings which i get when i use react-data-grid

**Please check if the PR fulfills these requirements**
- [*] The commit message follows our guidelines: https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[*] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
App throw warning about prop types from react...
https://github.com/adazzle/react-data-grid/issues/744

**What is the new behavior?**
App not works very well, i receive new warning "Calling PropTypes validators directly is not supported by the `prop-types` package..."

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by HackedBeat** [comment]
@GlebDolzhikov
Please, replace the double quotes with single quotes: _**"prop-types"**_ to _**'prop-types'**_

**Comment by GlebDolzhikov** [comment]
Ok! i will try to find time to fix validator issue also, maybe this week...

**Comment by iGitScor** [comment]
Hi,

Any info about this pull request ? 

Thank you

**Comment by malonecj** [comment]
Hi, thanks very much for the pull request. Sorry, about the lack of responses. I have been away for some time and am just getting back into it. We can merge this PR if you fix the lint errors, and resolve the conflicts in the branch.

**Comment by Nevosis** [comment]
Hello,

Do you need help fixing those lint error ? Would like it merged

**Comment by giulianf** [comment]
What about this PR?

**Comment by amanmahajan7** [comment]
`PropTypes` have been been migrated to separate `prop-types` package  #954.

**Pull request closed without merging**
