### PR TITLE
Convert `createReactClass` components to functional or class components

### LINKED ISSUE #978: Getting getDefaultProps warnings with react 15.6+
### Which version of React JS are you using?

✅ Officially supported ✅
- [ ] v15.4.x

⚠️ Not officially supported, expect warnings ⚠️
- [ ] v15.5.x
- [x] v15.6.x

☣️ Not officially supported, expect warnings and errors ☣️
- [ ] v16.x.x

---

### Which browser are you using?

✅ Officially supported ✅
- [ ] IE 9 / IE 10 / IE 11
- [ ] Edge
- [x] Chrome

⚠️ Not officially supported, but "should work" ⚠️
- [ ] Firefox
- [ ] Safari

---

### I'm submitting a ...

- [x] 🐛 Bug Report
- [ ] 💡 Feature Request

> 👋 Need general support? Not sure about how to use React itself, or how to get started with the Grid?
> Please do not submit support request here. Instead see

> https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md

---

### Issue Details
current behavior:
```
Warning: getDefaultProps is only used on classic React.createClass definitions. Use a static property named `defaultProps` instead.
```
image

desired behavior: no warnings

motivation: less noise in console warnings and compatibility to upgrade React

### PR DESCRIPTION
**Pull request by amanmahajan7**
## Description
Convert `createReactClass` components to functional or class components

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
`React 15.5` deprecated `React.createClass` and `React data grid` switched to `create-react-class` package as recommended by the Facebook team.

**What is the new behavior?**
Components that can be converted to `class` or `functional` components are migrated. Remaning components that are still using `mixins` will be migrated in a separate PR

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by jpdriver** [comment]
@amanmahajan7 will this be tested on React 15.5+ and React 16 too, or only React 15.4?

**Comment by amanmahajan7** [comment]
@jpdriver I was planning on testing with React 15.5+ but if we decide to keep `createReactClass` then I will test with `React 16` also. Apart from the already fixed files, there are additional 9 files that use `mixins` and cannot be converted easily
I think there are two ways to fix these warnings temporarily
1. Import the `dev` version of `createReactClass`. `const createReactClass = require('create-react-class/create-react-class');` Bundling the `dev` version would increase the bundle size but this can be ignored for now
As we are bundling `create-react-class` package with `react-data-grid`, webpack strips out the code that sets the`isReactClassApproved` [flag](https://github.com/facebook/react/blob/v15.5.4/addons/create-react-class/create-react-class.js#L713) and as `React` does not find this flag, it logs `development` time warnings (false positive). This warning is logged every time a new `Element` is created or cloned so we are seeing a lot of these warnings. 
Both the `dev` and `prod` versions of `react-data-grid` are built with the `--release` [flag](https://github.com/adazzle/react-data-grid/blob/master/package.json#L11), I think this flag should only be set for `prod` build,

2. Revert back to `React.createClass`. This will log a single dev time deprecation warning for `createClass`. For `React 16` this [patch](https://github.com/adazzle/react-data-grid/issues/744#issuecomment-333890937) will need to used. 

@jpdriver @malonecj what are you thoughts? Any other ideas? Also for the next major version we should set `prop-types` and `create-react-class` (if still used) as _peer_ dependencies

**Comment by jpdriver** [comment]
Remember though -- this issue is directly caused by React 16. Facebook put deprecation warnings in the release before React 16, and then deliberately made this throw in React 16. Whatever the ultimate fix is, I think it needs to be tested on 15.4, 15.5, and 16. We need to ensure the latter two don't log warnings and errors respectively.

I maintain that the cleanest, quickest, and most likely best solution is to revert the original PRs. Trying to screw about with different dev and prod versions / bundling an entire Facebook library alongside our own source / deliberately overriding React internal flags, etc. are all just messy solutions.

We weren't ready to take the PRs in the first place. I could see the script errors on the branch, so I'm not sure how that was missed or how it was checked internally before merging. But even so, the underlying grid architecture fundamentally isn't compatible right now, and we should've been aware of that. What we have dates from the React 11 / Prometheus Research days.

I strongly suggest we ship that patch as an invisible wrapper for the Grid, and then it wouldn't matter which version of React anyone was on, nobody would see warnings, and we'd have enough time to properly sort our internal architecture out for full compatibility.

I'd be happy to set that up in a branch if you guys want to play around with the result and confirm it, but I'll only bother doing that if you're open to considering it as the solution.

Also for what it's worth, at one point I separately started working on removing / converting the Mixins. Some of them are straight forward because they're only consumed by single components (the `ScrollMixins` are an example of that) but the ones we need to properly migrate to higher order components are mostly the `DOM` / `Column` ones.

**Comment by amanmahajan7** [comment]
@jpdriver, I completely agree with you that we should not be bundling Facebook libraries (`prop-types` and `create-react-class`) and this is the root cause of the problem. IMO removing these libraries from the bundle and specifying them as _peer_ dependencies would solve all the issues (except the `prop-types` warning you mentioned) but this change would probably require a major bump. I wasn't sure how to handle the versioning in this case.

It seems like we have two options
1) Like you mentioned, revert the original PRs and provide a wrapper. IMO this wrapper is also a bit hacky and to use this wrapper one must install `prop-types` and `create-react-class` packages.

```js
// temporaryHackForReactDataGrid.js: import this file before react-data-grid

require('react').PropTypes = require('prop-types');
require('react').createClass = require('create-react-class');
```
2) Keep the original PRs and specify `prop-types` and `create-react-class` as externals so webpack does not bundle them with `react-data-grid`. This also requires installing `prop-types` and `create-react-class` packages so in that regard it is similar to the first approach. `create-react-class`  was specifically designed for the projects that are not ready to migrate to `React 16` which `react-data-grid` is due to `mixins`. We this approach we can incrementally work on removing 
- Mixins
- [PropTypes warning](https://github.com/adazzle/react-data-grid/pull/954#issuecomment-332809999) 

I am personally inclined towards the 2nd option as a lot or work was put in to migrate `React.PropTypes` and `React.createClass` but I am fine with the first option as well. I would like to hear @malonecj  take on this issue.

**Comment by jpdriver** [comment]
@amanmahajan7 @malonecj ok -- how about we validate option 2 first, and confirm that there are no issues with that on React 15.4 / 15.5 / 16?

if there are, we'll fall back to option 1.

**Comment by jpdriver** [comment]
to be honest I don't think it would, but I'm happy to be proven wrong and right now we don't know for certain.

so the next move should be do a spike, investigate / validate, and if I'm wrong -- great! -- and if not then we fall back to option 1.

**Comment by amanmahajan7** [comment]
The build process bundles `createReactClass` package with `process.env.NODE_ENV` flag set to `production`. This strips out any `development` time code from the `createReactClass` package which includes the [block that sets the `isReactClassApproved` flag](https://github.com/facebook/react/blob/v15.5.4/addons/create-react-class/create-react-class.js#L719). 

The `development` version of `React` [logs a warning if it does not find this flag](https://github.com/facebook/react/blob/7d27851bf4aa8129276614b62edf9ade4aaa4cbd/packages/react/src/ReactElementValidator.js#L233). 

If `create-react-class` is specified as a _peer_ dependency then it becomes the responsibility of individual projects to include the correct files
- `development` version of `React` and `create-react-class` minified with webpack or any other build tool
or
- `production` version of `React` and `create-react-class` 

Again this theory must be tested and it case it fixes the warnings should the major version be bumped?

**Comment by Swagetha** [comment]
Any news on this?

**Comment by amanmahajan7** [comment]
I published a [new repository](https://github.com/amanmahajan7/react-data-grid/pull/1) with `create-react-class` and `prop-types` specified as `peer` dependencies and there are no more `getDefaultProps` warnings

Original (create-react-grid)
https://codesandbox.io/s/3z3lq9zn1

Fork (react-data-grid-aman)
https://codesandbox.io/s/409mmpynp4 react 15.6.2
https://codesandbox.io/s/k0j07n81nv react 16.2.0

@jpdriver @malonecj

**Comment by achillesrasquinha** [comment]
HURRAY!

**Pull request merged**
