### PR TITLE
Fix: re-focus the mask when it's updated, otherwise it will lose focus

### PR DESCRIPTION
**Pull request by qili26**
## Description
A few sentences describing the overall goals of the pull request's commits.

**Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines: https://github.com/adazzle/react-data-grid/blob/master/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x")
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Other... Please describe:
```

**What is the current behavior?** (You can also link to an open issue here)
When cell is being selected, clicking on the same cell will make the mask div lost focus.

**What is the new behavior?**
Re-focus the mask whenever it's updated while in boundary.

**Does this PR introduce a breaking change?** (check one with "x")
```
[ ] Yes
[x] No
```

If this PR contains a breaking change, please describe the impact and migration path for existing applications: ...

**Other information**:

### CODE REVIEW

**Comment by qili26** [comment]
let me try that action.

**Comment by qili26** [comment]
@MayhemYDG 
I re-run in my local and it's working after performing certain actions (clicking inside grid / outside grid, tabbing), could you be more specific for your example?

**Comment by MayhemYDG** [comment]
@qili26 let's say for example we update the `columns` prop from outside the grid, this should trigger `componentDidUpdate`, which will then call `this.focus()`. I think.
@amanmahajan7 wdyt?

**Comment by qili26** [comment]
I believe `isCellWithinBounds` will handle this, if it's within boundary, it's OK to re-focus, if it's out of boundary, this code will not run.

**Pull request closed without merging**
