### PR TITLE
Remove support for react-grid-Row--{even,odd}

### PR DESCRIPTION
**Pull request by MayhemYDG**
Users can style even/odd rows using proper CSS selectors.

### CODE REVIEW

**Comment by qili26** [comment]
I believe it's a breaking change, maybe we should add some description to Change.md

**Comment by MayhemYDG** [comment]
We're doing a lot of breaking changes right now, we'll document it all at some point I guess.

**Comment by qili26** [comment]
I am just thinking it's easy to lose track later, maybe in the title we add `Break`, then it will be easier for us to find which merge contains the break changes later, which are only the tsfying?

**Comment by MayhemYDG** [comment]
I want to clean up all the css and prefix every class names with `rdg`, so maybe we'll just have a single line in the changelog to mention that.

**Comment by qili26** [comment]
That would work.

**Comment by MayhemYDG** [comment]
Actually `nth-child()` selectors wouldn't work since we only render the visible rows only.
We can still remove those classes if we don't care to support them I guess.

**Comment by MayhemYDG** [comment]
This is actually used and `:nth-child()` is not a viable alternative, so I'm closing this.

**Pull request closed without merging**
